name: 01 - CWVJ Flask CI Pipeline

on:
  push:

jobs:
  flask-ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: docker build -t python-flask-app:v1.0.0 .

      - name: Run Container
        run: docker run -d -p 5000:5000 --name python-flask-container python-flask-app:v1.0.0

      - name: Smoke Test
        run: |
          sleep 5
          curl http://localhost:5000/health